routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\Dashboard\Admin\LoginController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


// Route::group(
//     [
//         'prefix' => LaravelLocalization::setLocale(),
//         'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
//     ],
//     function () {

Route::prefix('admin')->middleware('guestAdmin')->group(function () {
    Route::get('login', [LoginController::class, 'get']);
    Route::post('login_post', [LoginController::class, 'post']);

});

Route::prefix('dashboard')->name('dashboard.')->middleware('admin')->group(function () {
    // home page
    Route::get('/', [HomeController::class, 'index'])->name('home');
    // Route::get('lang/{lang}', ['ar' => 'lang.switch', 'uses' => LanguageController::class, 'switchLang']);

    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);


});

//     }
// );
// Route::get('/', function () {
//     return view('dashboard/dashboard');
// });

// php artisan migrate

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// php artisan make:migration create_admins_table
// php artisan migrate
// php artisan make:controller Dashboard/Admin/AdminsController --model=Admins
// php artisan make:middleware DashboardGuest

app/Http/Controllers/Dashboard/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Validator;

class AdminController extends Controller
{
    public function index()
    {
        $data = Admins::all();
        return view('dashboard.admin.index', compact('data'));
    }
    public function create()
    {

        return view('dashboard.admin.create');
    }
    public function store()
    {
        // dd(request()->all());
        $this->validate(
            request(),
            [
                'username' => 'required|string|min:3',
                'email' => 'required|email|unique:admins,email',
                'password' => 'required|string|confirmed',
            ]
        );
        $create = Admins::create([
            'username' => request()->username,
            'email' => request()->email,
            'password' => Hash::make(request()->password),
        ]);
        if (!$create) {
            return back()->with('error', 'حدث شئ ما خطأ يرجى المحاولة مرة أخرى');
        }
        return redirect('dashboard')->with('success', 'تم إضافة المدير بنجاح');
    }

    public function delete($id)
    {

        Validator::make(
            ['id' => $id],
            ['id' => 'required|integer|exists:admins,id'],
            []
        )->validate();

        $admin = Admins::find(request()->id);
        if (!$admin->delete()) {
            return back()->with('error', 'حدث شئ ما خطأ يرجى المحاولة مرة أخرى');
        }
        return back()->with('success', 'تم حذف المدير');
    }
}

app/Http/Controllers/Dashboard/Admin/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class ChangePasswordController extends Controller
{
    public function get()
    {
        return view('dashboard.admin.changePassword');
    }

    public function post()
    {
        //        dd(request()->all());
        $this->validate(request(), [
            'old_password' => 'required|string|max:255',
            'password' => 'required|string|min:8|confirmed|max:255',

        ]);

        if (Hash::check(request()->old_password, auth()->guard('admin')->user()->password)) {
            $admin = Admins::where('id', auth()->guard('admin')->user()->id)->first();
            $admin->password = Hash::make(request()->password);
            $save = $admin->save();
            if (!$save) {
                session()->flash('error', 'خطأ في حفظ البيانات الجديدة');
                return redirect()->back();
            }
            session()->flash('success', 'تم تحديث كلمة المرور بنجاح');
            return redirect('/dashboard');
        } else {
            session()->flash('error', 'كلمة المرور غير متطابقة');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Dashboard/Admin/ForgetPasswordController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use Validator;
use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Http\Controllers\Controller;

class ForgetPasswordController extends Controller
{
    public function forgetPassword()
    {
        return view('dashboard.admin.forgetPassword');
    }

    public function forgetPasswordPost()
    {
        //        dd(request()->all());
        $this->validate(request(), ['email' => 'required|email|exists:admins,email|max:191',]);
        $token = $this->randToken();
        $admin = Admins::where('email', request()->email)->first();
        $admin->reset_password_code = $token;
        $admin->save();
        $sendMail = $this->resetPasswordMail(request()->email, $token);
        if (!$sendMail) {
            return back()->with('message', 'خطأ لم يتم الإرسال');
        }

        return redirect('admin/login')->with('success', 'تم إرسال رابط إستعادة كلمة المرور');

    }

    public function resetPassword($email, $token)
    {
        validator::make(
            request()->all(),
            ['email' => $email, 'token' => $token],
            [
                'email' => 'required|email,exists:admins,email',
                'token' => 'required|email,exists:admins,reset_password_code',
            ]
        )->validate();
        session()->put('resetEmail', $email);
        session()->put('resetToken', $token);

        return view('dashboard.admin.resetPassword');
    }

    public function resetPasswordPost()
    {
        //        dd(request()->all());
        if (!session()->has('resetEmail') || !session()->has('resetToken')) {
            session()->flash('message', 'انتهت صلاحية هذا الرابط');
            return redirect('admin/login');
        }
        $email = session()->get('resetEmail');
        $token = session()->get('resetToken');
        $admin = Admins::where('email', $email)->where('reset_password_code', $token)->first();
        if (!$admin) {
            return back()->with('message', 'البيانات غير صحيحة');
        }
        validator::make(request()->all(), [
            'password' => 'required|confirmed|max:191:min:8',
            'password_confirmation' => 'required',
        ])->validate();
        $admin->password = Hash::make(request()->password);
        $admin->reset_password_code = null;
        $admin->save();
        session()->forget('resetEmail');
        session()->forget('resetToken');
        return redirect('/admin/login')->with('success', 'تم تحديث كلمة المرور بنجاح');

    }

    protected function randToken()
    {
        $token = md5(rand(1000000000, 9999999999));
        return (Admins::where('reset_password_code', $token)->first()) ? $this->randToken() : $token;

    }
    protected function resetPasswordMail($email, $token)
    {

        $data = array("body" => request()->root() . "/admin/reset-password/" . $email . "/" . $token);

        Mail::send('dashboard.admin.resetPasswordEmail', $data, function ($message) use ($email) {
            $message->to($email)
                ->subject(' Reset Password ');
            $message->from('no-reply@dayForce.com', 'dayForce.com');
        });
        if (Mail::failures()) {
            return false;
        }
        return true;
    }
}

app/Http/Controllers/Dashboard/Admin/LoginController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class LoginController extends Controller
{
    public function get()
    {
        return view('dashboard.admin.login');
    }

    public function post()
    {
        //       dd(request()->all());
        $this->validate(request(), [
            'email' => 'required|email|max:225',
            'password' => 'required|string|min:8|max:35',
        ]);


        $remember = request()->has('remember') ? true : false;
        $credentials = array('email' => request()->email, 'password' => request()->password);
        $checkLogin = Auth::guard('admin')->attempt($credentials, $remember);
        if (!$checkLogin) {
            session()->flash('message', 'البيانات غير صحيحة');
            return redirect('admin/login');

        }
        return redirect('/dashboard/');

    }

    public function logout()
    {
        auth()->guard('admin')->logout();
        return redirect('/admin/login');
    }
}

resources/views/dashboard/admin/changePassword.blade.php
@extends('dashboard.layouts.app')
<!-- ============ Body content start ============= -->
@section('content')
    <div class="breadcrumb">
        <a href="{{route('dashboard.home')}}"><h1>الرئيسية</h1></a>
        <ul>
            <li><a> تغير كلمة المرور</a></li>
        </ul>
    </div>


    <div class="separator-breadcrumb border-top"></div>

        <div class="row">
        <div class="col-md-10">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="card-title mb-3"><strong class="text-primary">تغير كلمة المرور</strong> </div>
                </div>
                <div class="card-body">
                    <form id="change-pwd" action="{{route('dashboard.changePassword.post')}}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6 form-group mb-3">
                                <label for="old_password">كلمة المرور القديمة</label>
                                <input type="text" class="form-control" name="old_password" id="old_password" placeholder="كلمة المرور القديمة" autocomplete="off">
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="password">كلمة المرور الجديدة</label>
                                <input type="password" class="form-control" name="password" id="password" placeholder="كلمة المرور الجديدة">
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="password_confirmation">تأكيد كلمة المرور الجديدة</label>
                                <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="تأكيد كلمة المرور الجديدة">
                            </div>



                            <div class="col-md-12">
                                <button class="btn btn-primary">حفظ</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection
<!-- ============ Body content End ============= -->
@section('js')
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script>
        $("#change-pwd").validate({
            // Specify the validation rules
            rules: {
                old_password: {
                    required: true,
                },
                password: {
                    required: true,
                    minlength:8,
                },
                password_confirmation: {
                    required: true,
                },

            },
            // Specify the validation error messages
            messages: {
                old_password: {
                    required: 'يرجى ادخال كلمة المرور القديمة ',
                },
                password: {
                    required: 'يرجى ادخال كلمة المرور الجديدة ',
                    minlength:'كلمة المرور يجب أن تكون 8 حروف على الأقل',
                },
                password_confirmation: {
                    required: 'يرجى تأكيد كلمة المرور الجديدة ',
                },
            },
            submitHandler: function (form) {
                form.submit();
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                $(element).closest('.form-group').find('.glyphicon').removeClass('glyphicon-ok').addClass('glyphicon-remove');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
                $(element).closest('.form-group').find('.glyphicon').removeClass('glyphicon-remove').addClass('glyphicon-ok');
            },
            errorElement: 'span',
            errorClass: 'text-danger',
            errorPlacement: function (error, element) {
                if (element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else if (element.closest('.form-group').find('.cke').length) {
                    error.appendTo(element.closest('.form-group'));
                } else {
                    error.insertAfter(element);
                }
            }
        });
    </script>
    @endsection

resources/views/dashboard/admin/create.blade.php
@extends('dashboard.layouts.app')

<!-- ============ Body content start ============= -->
@section('content')
    {{-- <div class="breadcrumb">
        <a href="{{route('dashboard.home')}}"><h1>الرئيسية</h1></a>
        <ul>
            <li><a> أضافة مدير</a></li>
        </ul>
    </div> --}}

    <div class="separator-breadcrumb border-top"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="card-title mb-3"> <strong class="text-primary">الاضافة</strong> </div>
                </div>
                @include('dashboard.layouts.message')

                <div class="card-body">
                    <form id="change-pwd" action="{{url('admin/store')}}" method="POST">
                        @method("POST")
                        @csrf
                        <div class="row">
                            <div class="col-md-6 form-group mb-3">
                                <label for="username">الإسم</label>
                                <input type="text" class="form-control" name="username" id="username" placeholder="الإسم" value="{{old('username')}}" autocomplete="off">
                                @if ($errors->has('username'))
                                    <span class="text-danger" role="alert">
                                        <strong>الإسم مطلوب</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="email">البريد الإلكتروني</label>
                                <input type="email" class="form-control" name="email" id="email" placeholder="البريد الإلكتروني" value="{{old('email')}}" autocomplete="off">
                                @if ($errors->has('email'))
                                    <span class="text-danger" role="alert">
                                        <strong>البريد الإلكتروني مطلوب</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="password">كلمة المرور</label>
                                <input type="password" class="form-control" name="password" id="password" placeholder="كلمة المرور ">
                                @if ($errors->has('password'))
                                    <span class="text-danger" role="alert">
                                        <strong>كلمه المرور مطلوبه ويجب ان لا تقل عن 8 حروف او ارقام</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-6 form-group mb-3">
                                <label for="password_confirmation">تأكيد كلمة المرور</label>
                                <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="تأكيد كلمة المرور ">
                                @if ($errors->has('password_confirmation'))
                                    <span class="text-danger" role="alert">
                                        <strong>يجب تأكيد كلمة المرور</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-12">
                                <button class="btn btn-primary">حفظ</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>


@endsection
<!-- ============ Body content End ============= -->
@section('js')
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script>
        $("#form").validate({
            // Specify the validation rules
            rules: {
                name: {
                    required: true,
                    alpha: true
                },
                url: {
                    required: true,
                    url:true,
                },

            },
            // Specify the validation error messages
            messages: {
                name: {
                    required: 'يرجى إدخال اسم الموقع ',
                    alpha: 'يجب ان يتكون اسم الموقع من حروف فقط ',
                },
                url: {
                    required: 'يرجى إدخال رابط الموقع  ',
                    url:'برجاء ادخال رابط صحيح',
                },
            },
            submitHandler: function (form) {
                form.submit();
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                $(element).closest('.form-group').find('.glyphicon').removeClass('glyphicon-ok').addClass('glyphicon-remove');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
                $(element).closest('.form-group').find('.glyphicon').removeClass('glyphicon-remove').addClass('glyphicon-ok');
            },
            errorElement: 'span',
            errorClass: 'help-block',
            errorPlacement: function (error, element) {
                if (element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else if (element.closest('.form-group').find('.cke').length) {
                    error.appendTo(element.closest('.form-group'));
                } else {
                    error.insertAfter(element);
                }
            }
        });
    </script>

@endsection

resources/views/dashboard/admin/forgetPassword.blade.php
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Saudi Clubs | Login</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{{asset("assets/styles/css/themes/lite-purple.min.css")}}">
</head>

<body class="text-right">
<div class="auth-layout-wrap" style="background-image: url({{asset('assets/images/photo-wide-4.jpg')}})">
    <div class="auth-content">
        <div class="card o-hidden" >
            <div class="row align-content-center">
                <div class="col-md-12 text-center">
                    <div class="p-4">
                        <div class="auth-logo text-center mb-4">
                            <img src="{{asset("assets/images/logo.png")}}" alt=""/>
                        </div>
                        <h1 class="mb-3 text-18" style="color: #5504a5;">إستعادة كلمة المرور</h1>
                        @include('dashboard.layouts.message')
                        <form action="{{route('admin.forgetPassword.post')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="email" style="color: #5504a5;">البريد الإلكتروني</label>
                                <input id="email" name="email" class="form-control form-control-rounded" type="email" autocomplete="off" required>
                                @if ($errors->has('email'))
                                    <span class="text-danger" role="alert">
                                        <strong>البريد الالكتروني مطلوب ويجب ان يكون صحيح</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="mt-3 ">
                                <div class="text-right">
                                    <a href="{{url('admin/login')}}" style="color: #5504a5;"><u>تسجيل الدخول</u></a>
                                </div>
                            </div>
                            <button class="btn btn-rounded btn-primary btn-block mt-2">إرسال</button>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="{{asset("assets/js/vendor/jquery-3.3.1.min.js")}}"></script>
<script src="{{asset("assets/js/vendor/bootstrap.bundle.min.js")}}"></script>
<script src="{{asset("assets/js/es5/script.min.js")}}"></script>
</body>

</html>

resources/views/dashboard/admin/index.blade.php
@extends('dashboard.layouts.app')

<!-- ============ Body content start ============= -->
@section('content')
        <div class="breadcrumb">
            <a href="{{route('dashboard.home')}}"><h1>الرئيسية</h1></a>
            <ul>
                <li>قائمة المديرين</li>
            </ul>
        </div>
        <div class="separator-breadcrumb border-top"></div>

        <!-- end of row -->

        <div class="row mb-4">
            <div class="col-md-12 mb-4">
                <div class="card text-left">
                    <div class="card-header">
                        <div class="card-title mb-3">
                            <strong class="text-primary"> قائمة المديرين</strong>
                            <span class="align-baseline" style="display:inline;">
                                <a class="btn btn-primary " href="{{url('dashboard/admin/create')}}" style="float: left">
                                <i class="i-Add align-middle" style="font-size: 17px; font-weight: 600;"></i> إضافة مدير  </a>
                            </span>

                        </div>
                    </div>
                    @include('dashboard.layouts.message')
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="alternative_pagination_table" class="display table table-striped table-bordered" style="width:100%">
                                <thead>
                                <tr>
                                    <th>الإسم </th>
                                    <th>البريد الإلكتروني </th>
                                    <th>التحكم </th>

                                </tr>
                                </thead>
                                <tbody>
                                @if(count($data)>0 && !empty($data))
                                    @foreach($data as $item)
                                        <tr>
                                            <td>{{$item->username}}</td>
                                            <td>{{$item->email}}</td>
{{--                                            @if($item->status===1)--}}
{{--                                                <td style="text-align: center;"><a  href="/sites/changeStatus/{!! $item->id !!}"  class="badge badge-success status-btn" style="width:80px;height: 25px;padding:auto;margin:auto;--}}
{{--                                 padding-top: 7px; font-size: small">نشط</a></td>--}}
{{--                                            @else--}}
{{--                                                <td style="text-align: center;"><a  href="/sites/changeStatus/{!! $item->id !!}"  class="badge badge-danger status-btn" style="width:80px;height: 25px;padding:auto;margin:auto;--}}
{{--                                   padding-top: 7px; font-size: small">غير نشط</a></td>--}}
{{--                                            @endif--}}
                                            <td style="text-align: center;">
{{--                                                <a href="/sites/edit/{{$item->id }}" class="text-success mr-2">--}}
{{--                                                    <i class="nav-icon i-Pen-2 font-weight-bold " ></i>--}}
{{--                                                </a>--}}
                                                @if($item->id != auth('admin')->id())
                                                    <a href="{{url('dashboard/admin/delete/'.$item->id)}}" class="text-danger mr-2">
                                                        <i class="nav-icon i-Close-Window font-weight-bold delete-btn"></i>
                                                    </a>
                                                @endif
                                            </td>

                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>

                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end of col -->

        </div>
        <!-- end of row -->


@endsection
<!-- ============ Body content End ============= -->
@section('js')
    <script>
        $(document).ready(function() {

            $("#alternative_pagination_table").on('click', '.status-btn', function () {
                var id = $(this).attr('id');
                var r = confirm("هل انت متاكد من تغيير الحالة");
                if (!r) {
                    return false
                }
            });

            $("#alternative_pagination_table").on('click', '.delete-btn', function () {
                var id = $(this).attr('id');
                var r = confirm("هل انت متاكد من عمليه الحذف ؟");
                if (!r) {
                    return false
                }
            });
        });
    </script>

@endsection

resources/views/dashboard/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Webmin - Bootstrap 4 & Angular 5 Admin Dashboard Template" />
    <meta name="author" content="potenzaglobalsolutions.com" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    @include('dashboard.layouts.head')
</head>

<body>
<div class="auth-layout-wrap" style="background-color: #10152d;">
    <div class="auth-content">
        <div class="card o-hidden" >
            <div class="row align-content-center">
                <div class="col-md-12 text-center">
                    <div class="p-4">
                        <div class="auth-logo text-center mb-4">
                          <!--  <img src="{{asset("assets/images/logo.png")}}" alt=""/> -->
                        </div>
                        <h1 class="mb-3 text-18" style="color: #2f47c2;">الدخول إلى لوحة التحكم</h1>
                        @include('dashboard.layouts.message')
                        <form action="{{url('admin/login_post')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="email" style="color: #2f47c2;">البريد الإلكتروني</label>
                                <input id="email" name="email" class="form-control form-control-rounded" type="email" autocomplete="off" required>
                                @if ($errors->has('email'))
                                    <span class="text-danger" role="alert">
                                        <strong>البريد الالكتروني مطلوب ويجب ان يكون صحيح</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="password" style="color: #2f47c2;">كلمة المرور</label>
                                <input id="password" name="password" class="form-control form-control-rounded" type="password">
                                @if ($errors->has('password'))
                                    <span class="text-danger" role="alert">
                                        <strong>كلمه المرور مطلوبه ويجب ان لا تقل عن 8 حروف او ارقام</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="mt-3 ">
                                <div class="text-left" style="float: right">
                                    <label class="checkbox checkbox-outline-info " >
                                        <input type="checkbox" name="remember" >
                                        <span>تذكرني</span>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="text-right">
{{--                                    <a href="{{route('admin.forgetPassword.get')}}" style="color: #2f47c2;"><u>نسيت كلمة المرور</u></a>--}}
                                </div>
                            </div>
                            <button class="btn btn-rounded btn-primary btn-block mt-2">تسجيل الدخول</button>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="{{asset("assets/js/vendor/jquery-3.3.1.min.js")}}"></script>
<script src="{{asset("assets/js/vendor/bootstrap.bundle.min.js")}}"></script>
<script src="{{asset("assets/js/es5/script.min.js")}}"></script>
</body>

</html>

resources/views/dashboard/admin/resetPasswordEmail.blade.php
<html>
<head>

</head>
<body>

<a href="{{$body}}"> Click Here To Reset Your Password</a>
</body>
</html>