routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\Dashboard\Admin\LoginController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


// Route::group(
//     [
//         'prefix' => LaravelLocalization::setLocale(),
//         'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
//     ],
//     function () {

Route::prefix('admin')->middleware('guestAdmin')->group(function () {
    Route::get('login', [LoginController::class, 'get']);
    Route::post('login_post', [LoginController::class, 'post']);

});

Route::prefix('dashboard')->name('dashboard.')->middleware('admin')->group(function () {
    // home page
    Route::get('/', [HomeController::class, 'index'])->name('home');
    // Route::get('lang/{lang}', ['ar' => 'lang.switch', 'uses' => LanguageController::class, 'switchLang']);

    Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);


});

//     }
// );
// Route::get('/', function () {
//     return view('dashboard/dashboard');
// });

// php artisan migrate

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// php artisan make:migration create_admins_table
// php artisan migrate
// php artisan make:controller Dashboard/Admin/AdminsController --model=Admins
// php artisan make:middleware DashboardGuest

app/Http/Controllers/Dashboard/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use Validator;

class AdminController extends Controller
{
    public function index()
    {
        $data = Admins::all();
        return view('dashboard.admin.index', compact('data'));
    }
    public function create()
    {

        return view('dashboard.admin.create');
    }
    public function store()
    {
        // dd(request()->all());
        $this->validate(
            request(),
            [
                'username' => 'required|string|min:3',
                'email' => 'required|email|unique:admins,email',
                'password' => 'required|string|confirmed',
            ]
        );
        $create = Admins::create([
            'username' => request()->username,
            'email' => request()->email,
            'password' => Hash::make(request()->password),
        ]);
        if (!$create) {
            return back()->with('error', 'حدث شئ ما خطأ يرجى المحاولة مرة أخرى');
        }
        return redirect('dashboard')->with('success', 'تم إضافة المدير بنجاح');
    }

    public function delete($id)
    {

        Validator::make(
            ['id' => $id],
            ['id' => 'required|integer|exists:admins,id'],
            []
        )->validate();

        $admin = Admins::find(request()->id);
        if (!$admin->delete()) {
            return back()->with('error', 'حدث شئ ما خطأ يرجى المحاولة مرة أخرى');
        }
        return back()->with('success', 'تم حذف المدير');
    }
}

app/Http/Controllers/Dashboard/Admin/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class ChangePasswordController extends Controller
{
    public function get()
    {
        return view('dashboard.admin.changePassword');
    }

    public function post()
    {
        //        dd(request()->all());
        $this->validate(request(), [
            'old_password' => 'required|string|max:255',
            'password' => 'required|string|min:8|confirmed|max:255',

        ]);

        if (Hash::check(request()->old_password, auth()->guard('admin')->user()->password)) {
            $admin = Admins::where('id', auth()->guard('admin')->user()->id)->first();
            $admin->password = Hash::make(request()->password);
            $save = $admin->save();
            if (!$save) {
                session()->flash('error', 'خطأ في حفظ البيانات الجديدة');
                return redirect()->back();
            }
            session()->flash('success', 'تم تحديث كلمة المرور بنجاح');
            return redirect('/dashboard');
        } else {
            session()->flash('error', 'كلمة المرور غير متطابقة');
            return redirect()->back();
        }
    }
}

app/Http/Controllers/Dashboard/Admin/ForgetPasswordController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use Validator;
use App\Models\Admins;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Http\Controllers\Controller;

class ForgetPasswordController extends Controller
{
    public function forgetPassword()
    {
        return view('dashboard.admin.forgetPassword');
    }

    public function forgetPasswordPost()
    {
        //        dd(request()->all());
        $this->validate(request(), ['email' => 'required|email|exists:admins,email|max:191',]);
        $token = $this->randToken();
        $admin = Admins::where('email', request()->email)->first();
        $admin->reset_password_code = $token;
        $admin->save();
        $sendMail = $this->resetPasswordMail(request()->email, $token);
        if (!$sendMail) {
            return back()->with('message', 'خطأ لم يتم الإرسال');
        }

        return redirect('admin/login')->with('success', 'تم إرسال رابط إستعادة كلمة المرور');

    }

    public function resetPassword($email, $token)
    {
        validator::make(
            request()->all(),
            ['email' => $email, 'token' => $token],
            [
                'email' => 'required|email,exists:admins,email',
                'token' => 'required|email,exists:admins,reset_password_code',
            ]
        )->validate();
        session()->put('resetEmail', $email);
        session()->put('resetToken', $token);

        return view('dashboard.admin.resetPassword');
    }

    public function resetPasswordPost()
    {
        //        dd(request()->all());
        if (!session()->has('resetEmail') || !session()->has('resetToken')) {
            session()->flash('message', 'انتهت صلاحية هذا الرابط');
            return redirect('admin/login');
        }
        $email = session()->get('resetEmail');
        $token = session()->get('resetToken');
        $admin = Admins::where('email', $email)->where('reset_password_code', $token)->first();
        if (!$admin) {
            return back()->with('message', 'البيانات غير صحيحة');
        }
        validator::make(request()->all(), [
            'password' => 'required|confirmed|max:191:min:8',
            'password_confirmation' => 'required',
        ])->validate();
        $admin->password = Hash::make(request()->password);
        $admin->reset_password_code = null;
        $admin->save();
        session()->forget('resetEmail');
        session()->forget('resetToken');
        return redirect('/admin/login')->with('success', 'تم تحديث كلمة المرور بنجاح');

    }

    protected function randToken()
    {
        $token = md5(rand(1000000000, 9999999999));
        return (Admins::where('reset_password_code', $token)->first()) ? $this->randToken() : $token;

    }
    protected function resetPasswordMail($email, $token)
    {

        $data = array("body" => request()->root() . "/admin/reset-password/" . $email . "/" . $token);

        Mail::send('dashboard.admin.resetPasswordEmail', $data, function ($message) use ($email) {
            $message->to($email)
                ->subject(' Reset Password ');
            $message->from('no-reply@dayForce.com', 'dayForce.com');
        });
        if (Mail::failures()) {
            return false;
        }
        return true;
    }
}

app/Http/Controllers/Dashboard/Admin/LoginController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin;

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class LoginController extends Controller
{
    public function get()
    {
        return view('dashboard.admin.login');
    }

    public function post()
    {
        //       dd(request()->all());
        $this->validate(request(), [
            'email' => 'required|email|max:225',
            'password' => 'required|string|min:8|max:35',
        ]);


        $remember = request()->has('remember') ? true : false;
        $credentials = array('email' => request()->email, 'password' => request()->password);
        $checkLogin = Auth::guard('admin')->attempt($credentials, $remember);
        if (!$checkLogin) {
            session()->flash('message', 'البيانات غير صحيحة');
            return redirect('admin/login');

        }
        return redirect('/dashboard/');

    }

    public function logout()
    {
        auth()->guard('admin')->logout();
        return redirect('/admin/login');
    }
}

resources/views/dashboard/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/dashboard/layouts/footer-scripts.blade.php
<!-- jquery -->
<script src="{{ URL::asset('assets/js/jquery-3.3.1.min.js') }}"></script>
<!-- plugins-jquery -->
<script src="{{ URL::asset('assets/js/plugins-jquery.js') }}"></script>
<!-- plugin_path -->
<script>
    var plugin_path = 'js/';

</script>

<!-- chart -->
<script src="{{ URL::asset('assets/js/chart-init.js') }}"></script>
<!-- calendar -->
<script src="{{ URL::asset('assets/js/calendar.init.js') }}"></script>
<!-- charts sparkline -->
<script src="{{ URL::asset('assets/js/sparkline.init.js') }}"></script>
<!-- charts morris -->
<script src="{{ URL::asset('assets/js/morris.init.js') }}"></script>
<!-- datepicker -->
<script src="{{ URL::asset('assets/js/datepicker.js') }}"></script>
<!-- sweetalert2 -->
<script src="{{ URL::asset('assets/js/sweetalert2.js') }}"></script>
<!-- toastr -->
@yield('js')
<script src="{{ URL::asset('assets/js/toastr.js') }}"></script>
<!-- validation -->
<script src="{{ URL::asset('assets/js/validation.js') }}"></script>
<!-- lobilist -->
<script src="{{ URL::asset('assets/js/lobilist.js') }}"></script>
<!-- custom -->
<script src="{{ URL::asset('assets/js/custom.js') }}"></script>

resources/views/dashboard/layouts/footer.blade.php
<!-- Footer opened -->
 <footer class="bg-white p-4">
      <div class="row">
        <div class="col-md-6">
          <div class="text-center text-md-left">
              <p class="mb-0"> &copy; Copyright <span id="copyright"> <script>document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))</script></span>. <a href="#"> Webmin </a> All Rights Reserved. </p>
          </div>
        </div>
        <div class="col-md-6">
          <ul class="text-center text-md-right">
            <li class="list-inline-item"><a href="#">Terms & Conditions </a> </li>
            <li class="list-inline-item"><a href="#">API Use Policy </a> </li>
            <li class="list-inline-item"><a href="#">Privacy Policy </a> </li>
          </ul>
        </div>
      </div>
    </footer>
<!-- Footer closed -->

resources/views/dashboard/layouts/head.blade.php
<!-- Title -->
<title>@yield("title")</title>

<!-- Favicon -->
<link rel="shortcut icon" href="{{ URL::asset('assets/images/favicon.ico') }}" type="image/x-icon" />

<!-- Font -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Poppins:200,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900">
@yield('css')
<!--- Style css -->
<link href="{{ URL::asset('assets/css/style.css') }}" rel="stylesheet">

<!--- Style css -->
@if (App::getLocale() == 'en')
    <link href="{{ URL::asset('assets/css/ltr.css') }}" rel="stylesheet">
@else
    <link href="{{ URL::asset('assets/css/rtl.css') }}" rel="stylesheet">
@endif

resources/views/dashboard/layouts/main-header.blade.php
        <!--=================================
 header start-->
        <nav class="admin-header navbar navbar-default col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <!-- logo -->
            <div class="text-left navbar-brand-wrapper">
                <a class="navbar-brand brand-logo" href="index.html"><img src="assets/images/logo-dark.png"
                        alt=""></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="assets/images/logo-icon-dark.png"
                        alt=""></a>
            </div>
            <!-- Top bar left -->
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a id="button-toggle" class="button-toggle-nav inline-block ml-20 pull-left"
                        href="javascript:void(0);"><i class="zmdi zmdi-menu ti-align-right"></i></a>
                </li>
                <li class="nav-item">
                    <div class="search">
                        <a class="search-btn not_click" href="javascript:void(0);"></a>
                        <div class="search-box not-click">
                            <input type="text" class="not-click form-control" placeholder="Search" value=""
                                name="search">
                            <button class="search-button" type="submit"> <i
                                    class="fa fa-search not-click"></i></button>
                        </div>
                    </div>
                </li>
            </ul>

            <!-- top bar right -->
            <ul class="nav navbar-nav ml-auto">

                <div class="btn-group mb-1">
                    <button type="button" class="btn btn-light btn-sm dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        @if (App::getLocale() == 'ar')
                            {{ Config::get('languages')[App::getLocale()] }}


                            <img src="{{ URL::asset('assets/images/flags/EG.png') }}" alt="">
                        @else
                            {{ Config::get('languages')[App::getLocale()] }}
                            <img src="{{ URL::asset('assets/images/flags/US.png') }}" alt="">
                        @endif
                    </button>
                    <div class="dropdown-menu">
                        {{-- @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                <a class="dropdown-item" rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                                    {{ $properties['native'] }}
                                </a>
                        @endforeach --}}
                        @foreach (Config::get('languages') as $lang => $language)
                            @if ($lang != App::getLocale())
                                <a class="dropdown-item" href="{{ route('dashboard.lang.switch', $lang) }}">
                                    {{ $language }}</a>
                            @endif
                        @endforeach
                    </div>
                </div>
                {{-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ Config::get('languages')[App::getLocale()] }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    @foreach (Config::get('languages') as $lang => $language)
                        @if ($lang != App::getLocale())
                                <a class="dropdown-item" href="{{ route('dashboard.lang.switch', $lang) }}"> {{$language}}</a>
                        @endif
                    @endforeach
                    </div>
                </li> --}}
                <li class="nav-item fullscreen">
                    <a id="btnFullscreen" href="#" class="nav-link"><i class="ti-fullscreen"></i></a>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link top-nav" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="ti-bell"></i>
                        <span class="badge badge-danger notification-status"> </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-big dropdown-notifications">
                        <div class="dropdown-header notifications">
                            <strong>Notifications</strong>
                            <span class="badge badge-pill badge-warning">05</span>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">New registered user <small
                                class="float-right text-muted time">Just now</small> </a>
                        <a href="#" class="dropdown-item">New invoice received <small
                                class="float-right text-muted time">22 mins</small> </a>
                        <a href="#" class="dropdown-item">Server error report<small
                                class="float-right text-muted time">7 hrs</small> </a>
                        <a href="#" class="dropdown-item">Database report<small
                                class="float-right text-muted time">1
                                days</small> </a>
                        <a href="#" class="dropdown-item">Order confirmation<small
                                class="float-right text-muted time">2
                                days</small> </a>
                    </div>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link top-nav" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="true"> <i class=" ti-view-grid"></i> </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-big">
                        <div class="dropdown-header">
                            <strong>Quick Links</strong>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="nav-grid">
                            <a href="#" class="nav-grid-item"><i class="ti-files text-primary"></i>
                                <h5>New Task</h5>
                            </a>
                            <a href="#" class="nav-grid-item"><i class="ti-check-box text-success"></i>
                                <h5>Assign Task</h5>
                            </a>
                        </div>
                        <div class="nav-grid">
                            <a href="#" class="nav-grid-item"><i class="ti-pencil-alt text-warning"></i>
                                <h5>Add Orders</h5>
                            </a>
                            <a href="#" class="nav-grid-item"><i class="ti-truck text-danger "></i>
                                <h5>New Orders</h5>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown mr-30">
                    <a class="nav-link nav-pill user-avatar" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="false">
                        <img src="assets/images/profile-avatar.jpg" alt="avatar">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header">
                            <div class="media">
                                <div class="media-body">
                                    <h5 class="mt-0 mb-0">Michael Bean</h5>
                                    <span>michael-bean@mail.com</span>
                                </div>
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#"><i class="text-secondary ti-reload"></i>Activity</a>
                        <a class="dropdown-item" href="#"><i class="text-success ti-email"></i>Messages</a>
                        <a class="dropdown-item" href="#"><i class="text-warning ti-user"></i>Profile</a>
                        <a class="dropdown-item" href="#"><i class="text-dark ti-layers-alt"></i>Projects <span
                                class="badge badge-info">6</span> </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#"><i class="text-info ti-settings"></i>Settings</a>
                        <a class="dropdown-item" href="#"><i class="text-danger ti-unlock"></i>Logout</a>
                    </div>
                </li>
            </ul>
        </nav>

        <!--=================================
 header End-->

resources/views/dashboard/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Webmin - Bootstrap 4 & Angular 5 Admin Dashboard Template" />
    <meta name="author" content="potenzaglobalsolutions.com" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    @include('dashboard.layouts.head')
</head>

<body>

    <div class="wrapper">

        <!--=================================
 preloader -->

        <div id="pre-loader">
            <img src="assets/images/pre-loader/loader-01.svg" alt="">
        </div>

        <!--=================================
 preloader -->

        @include('dashboard.layouts.main-header')

        @include('dashboard.layouts.main-sidebar')

        <!--=================================
 Main content -->
        <!-- main-content -->
        <div class="content-wrapper">

            @yield('page-header')

            @yield('content')

            <!--=================================
 wrapper -->

            <!--=================================
 footer -->

            @include('dashboard.layouts.footer')
        </div><!-- main content wrapper end-->
    </div>
    </div>
    </div>

    <!--=================================
 footer -->

    @include('dashboard.layouts.footer-scripts')

</body>

</html>

resources/views/dashboard/layouts/message.blade.php
{{--@if (count($errors->all()) > 0)--}}
{{--    <div class="alert alert-danger alert-block">--}}
{{--        <i class="fa fa-ban"></i>--}}
{{--        <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>--}}

{{--        <ul>--}}
{{--            @foreach($errors->all() as $message)--}}
{{--                <li>{{ $message }}</li>--}}
{{--            @endforeach--}}
{{--        </ul>--}}
{{--    </div>--}}
{{--@endif--}}
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block session-box">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>
        @if(is_array($message))
            @foreach ($message as $m)
                <h4 class="text-success text-center">  {{ $m }}</h4>
            @endforeach
        @else
            <h4 style="text-align: center;">  {{ $message }}</h4>
        @endif
    </div>
@endif
@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block session-box">
        <i class="fa fa-ban"></i>
        <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>

        @if(is_array($message))
            @foreach ($message as $m)
                {{ $m }}
            @endforeach
        @else
            <h4 class="text-danger text-center" >{{ $message }}</h4>
        @endif
    </div>
@endif

@if ($message = Session::get('warning_message'))
    <div class="alert alert-warning alert-block session-box">
        <i class="fa fa-warning"></i>
        <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>

        @if(is_array($message))
            @foreach ($message as $m)
                {{ $m }}
            @endforeach
        @else
            <h4 style="text-align: center;"> {{ $message }}</h4>
        @endif
    </div>
@endif

@if ($message = Session::get('info_message'))
    <div class="alert alert-info alert-block session-box">
        <i class="fa fa-info"></i>
        <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>

        @if(is_array($message))
            @foreach ($message as $m)
                {{ $m }}
            @endforeach
        @else
            <h4 style="text-align: center;"> {{ $message }}</h4>
        @endif
    </div>
@endif